// Copyright 2021 Pascal Laenen

// Defines the API for sending and verifying OTP messages

// style guide https://developers.google.com/protocol-buffers/docs/style

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.2
// source: auth/otp.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestOtpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdempotencyKey string `protobuf:"bytes,1,opt,name=IdempotencyKey,proto3" json:"IdempotencyKey,omitempty"`
	// External refernece e.g. customerId, email, ...
	ExtenalReference string `protobuf:"bytes,2,opt,name=extenal_reference,json=extenalReference,proto3" json:"extenal_reference,omitempty"`
	// When an email is provided we will send an email otp
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// When an mobile number is providec we will send an sms otp
	Mobile string `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// Defines how long the otp will be valid once send
	// Default will be 5 min
	TtlSeconds string `protobuf:"bytes,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	// Defines the backoff coefficient for requesting a new otp
	// Default backoff coeficient = 2 and first time resend is set a 60 seconds
	BackoffCoefficient string `protobuf:"bytes,6,opt,name=backoff_coefficient,json=backoffCoefficient,proto3" json:"backoff_coefficient,omitempty"`
	// Defines how often a user can retry to verify a given otp
	// Default will be set to 3
	MaxRetries int32 `protobuf:"varint,7,opt,name=maxRetries,proto3" json:"maxRetries,omitempty"`
}

func (x *RequestOtpReq) Reset() {
	*x = RequestOtpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_otp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestOtpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOtpReq) ProtoMessage() {}

func (x *RequestOtpReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_otp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOtpReq.ProtoReflect.Descriptor instead.
func (*RequestOtpReq) Descriptor() ([]byte, []int) {
	return file_auth_otp_proto_rawDescGZIP(), []int{0}
}

func (x *RequestOtpReq) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *RequestOtpReq) GetExtenalReference() string {
	if x != nil {
		return x.ExtenalReference
	}
	return ""
}

func (x *RequestOtpReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RequestOtpReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *RequestOtpReq) GetTtlSeconds() string {
	if x != nil {
		return x.TtlSeconds
	}
	return ""
}

func (x *RequestOtpReq) GetBackoffCoefficient() string {
	if x != nil {
		return x.BackoffCoefficient
	}
	return ""
}

func (x *RequestOtpReq) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

type RequestOtpRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A nonce will be provided which has to be send back
	// when verifying the by SMS or Mobile phone provided otp
	Nonce string `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Retry will be possible adter the given time
	// first time 60 seconds then multiplied by the backoff_coefficient
	RetryDelaySeconds int32 `protobuf:"varint,2,opt,name=retry_delay_seconds,json=retryDelaySeconds,proto3" json:"retry_delay_seconds,omitempty"`
}

func (x *RequestOtpRes) Reset() {
	*x = RequestOtpRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_otp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestOtpRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOtpRes) ProtoMessage() {}

func (x *RequestOtpRes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_otp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOtpRes.ProtoReflect.Descriptor instead.
func (*RequestOtpRes) Descriptor() ([]byte, []int) {
	return file_auth_otp_proto_rawDescGZIP(), []int{1}
}

func (x *RequestOtpRes) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *RequestOtpRes) GetRetryDelaySeconds() int32 {
	if x != nil {
		return x.RetryDelaySeconds
	}
	return 0
}

type VerifyOptReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdempotencyKey string `protobuf:"bytes,1,opt,name=IdempotencyKey,proto3" json:"IdempotencyKey,omitempty"`
	// External refernece e.g. customerId, email, ...
	// Has to be the same as used when requesting an otp
	ExtenalReference string `protobuf:"bytes,2,opt,name=extenal_reference,json=extenalReference,proto3" json:"extenal_reference,omitempty"`
	// The provided nonce when requesting an otp
	Nonce string `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// The opt which was send by email or sms
	Otp string `protobuf:"bytes,4,opt,name=otp,proto3" json:"otp,omitempty"`
}

func (x *VerifyOptReq) Reset() {
	*x = VerifyOptReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_otp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyOptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOptReq) ProtoMessage() {}

func (x *VerifyOptReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_otp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOptReq.ProtoReflect.Descriptor instead.
func (*VerifyOptReq) Descriptor() ([]byte, []int) {
	return file_auth_otp_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyOptReq) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *VerifyOptReq) GetExtenalReference() string {
	if x != nil {
		return x.ExtenalReference
	}
	return ""
}

func (x *VerifyOptReq) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *VerifyOptReq) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type VerifyOtpRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Indicates if the
	Verified    bool  `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	RetriesLeft int32 `protobuf:"varint,2,opt,name=retriesLeft,proto3" json:"retriesLeft,omitempty"`
}

func (x *VerifyOtpRes) Reset() {
	*x = VerifyOtpRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_otp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyOtpRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOtpRes) ProtoMessage() {}

func (x *VerifyOtpRes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_otp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOtpRes.ProtoReflect.Descriptor instead.
func (*VerifyOtpRes) Descriptor() ([]byte, []int) {
	return file_auth_otp_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyOtpRes) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *VerifyOtpRes) GetRetriesLeft() int32 {
	if x != nil {
		return x.RetriesLeft
	}
	return 0
}

var File_auth_otp_proto protoreflect.FileDescriptor

var file_auth_otp_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x6f, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x61, 0x75, 0x74, 0x68, 0x22, 0x84, 0x02, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x4f, 0x74, 0x70, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x0e, 0x49, 0x64, 0x65, 0x6d,
	0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x49, 0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b, 0x65, 0x79,
	0x12, 0x2b, 0x0a, 0x11, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x65, 0x78, 0x74,
	0x65, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74,
	0x74, 0x6c, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x74, 0x74, 0x6c, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x2f, 0x0a, 0x13,
	0x62, 0x61, 0x63, 0x6b, 0x6f, 0x66, 0x66, 0x5f, 0x63, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69,
	0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x62, 0x61, 0x63, 0x6b, 0x6f,
	0x66, 0x66, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x6d, 0x61, 0x78, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x6d, 0x61, 0x78, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x55, 0x0a,
	0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4f, 0x74, 0x70, 0x52, 0x65, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e,
	0x6f, 0x6e, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x72, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x64, 0x65,
	0x6c, 0x61, 0x79, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x11, 0x72, 0x65, 0x74, 0x72, 0x79, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x53, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x22, 0x8b, 0x01, 0x0a, 0x0c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f,
	0x70, 0x74, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x0e, 0x49, 0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74,
	0x65, 0x6e, 0x63, 0x79, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x49,
	0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x2b, 0x0a,
	0x11, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x61,
	0x6c, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f,
	0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6f, 0x74, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f,
	0x74, 0x70, 0x22, 0x4c, 0x0a, 0x0c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f, 0x74, 0x70, 0x52,
	0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73, 0x4c, 0x65, 0x66, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73, 0x4c, 0x65, 0x66, 0x74,
	0x32, 0x7c, 0x0a, 0x0a, 0x4f, 0x74, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38,
	0x0a, 0x0a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4f, 0x74, 0x70, 0x12, 0x13, 0x2e, 0x61,
	0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4f, 0x74, 0x70, 0x52, 0x65,
	0x71, 0x1a, 0x13, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x4f, 0x74, 0x70, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x08, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x4f, 0x70, 0x12, 0x12, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x4f, 0x70, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f, 0x74, 0x70, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x07,
	0x5a, 0x05, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_auth_otp_proto_rawDescOnce sync.Once
	file_auth_otp_proto_rawDescData = file_auth_otp_proto_rawDesc
)

func file_auth_otp_proto_rawDescGZIP() []byte {
	file_auth_otp_proto_rawDescOnce.Do(func() {
		file_auth_otp_proto_rawDescData = protoimpl.X.CompressGZIP(file_auth_otp_proto_rawDescData)
	})
	return file_auth_otp_proto_rawDescData
}

var file_auth_otp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_auth_otp_proto_goTypes = []interface{}{
	(*RequestOtpReq)(nil), // 0: auth.RequestOtpReq
	(*RequestOtpRes)(nil), // 1: auth.RequestOtpRes
	(*VerifyOptReq)(nil),  // 2: auth.VerifyOptReq
	(*VerifyOtpRes)(nil),  // 3: auth.VerifyOtpRes
}
var file_auth_otp_proto_depIdxs = []int32{
	0, // 0: auth.OtpService.RequestOtp:input_type -> auth.RequestOtpReq
	2, // 1: auth.OtpService.VerifyOp:input_type -> auth.VerifyOptReq
	1, // 2: auth.OtpService.RequestOtp:output_type -> auth.RequestOtpRes
	3, // 3: auth.OtpService.VerifyOp:output_type -> auth.VerifyOtpRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_otp_proto_init() }
func file_auth_otp_proto_init() {
	if File_auth_otp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_auth_otp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestOtpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_otp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestOtpRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_otp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyOptReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_otp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyOtpRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auth_otp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_otp_proto_goTypes,
		DependencyIndexes: file_auth_otp_proto_depIdxs,
		MessageInfos:      file_auth_otp_proto_msgTypes,
	}.Build()
	File_auth_otp_proto = out.File
	file_auth_otp_proto_rawDesc = nil
	file_auth_otp_proto_goTypes = nil
	file_auth_otp_proto_depIdxs = nil
}
